# ~/.config/hypr/hyprqt6engine.conf

theme {
    color_scheme = /home/nbkt/dotfiles/colors/mocha-sapphire-qt6.colors
    icon_theme   = Papirus-Dark
    style        = hypr-style

    font          = JetBrainsMono Nerd Font
    font_fixed    = JetBrainsMono Nerd Font
}

misc {
    shortcuts_for_context_menus = true
}
