source = /home/justin/.cache/wal/colors-hyprland.conf

# BACKGROUND
background {
    monitor =
    path = screenshot
    blur_passes = 2
    contrast = 1
    brightness = 0.8
    vibrancy = 0.4
    vibrancy_darkness = 0.2
    noise = 0.1
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

auth {
    fingerprint:enabled = true
}
